const KEY = {
  GLOBAL: {
    USER: {
      USER_NAME: 'GLOBAL_USER_USER_NAME' as const,
      TYPE: 'GLOBAL_USER_TYPE' as const,
      NAME: 'GLOBAL_USER_NAME' as const,
      IS_SUBSCRIPTION: 'GLOBAL_USER_IS_SUBSCRIPTION' as const,
    },
  },
  FIND: {
    ID: {
      // NAME
      NAME: 'FIND_ID_NAME' as const,
      NAME_IS_ERR: 'FIND_ID_NAME_IS_ERR' as const,
      NAME_ERR_MSG: 'FIND_ID_NAME_ERR_ERR' as const,
      NAME_BLANK_ERR_MSG: 'FIND_ID_NAME_BLANK_ERR_MSG' as const,

      // PHONE
      PHONE: 'FIND_ID_PHONE' as const,
      PHONE_CONFIRM_MSG: 'FIND_ID_PHONE_CONFIRM_MSG' as const,
      PHONE_IS_ERR: 'FIND_ID_PHONE_IS_ERR' as const,
      PHONE_ERR_MSG: 'FIND_ID_PHONE_ERR_MSG' as const,
      PHONE_DUPLICATE_ERR_MSG: 'FIND_ID_PHONE_DUPLICATE_ERR_MSG' as const,
      PHONE_BLANK_ERR_MSG: 'FIND_ID_PHONE_BLANK_ERR_MSG' as const,
      PHONE_REGEX_ERR_MSG: 'FIND_ID_PHONE_REGEX_ERR_MSG' as const,
      PHONE_NOT_REQUESTED_AUTH_ERR_MSG: 'FIND_ID_PHONE_NOT_REQUESTED_AUTH_ERR_MSG' as const,

      // AUTH NUM
      AUTH_NUM: 'FIND_ID_AUTH_NUM' as const,
      AUTH_NUM_IS_ERR: 'FIND_ID_AUTH_NUM_IS_ERR' as const,
      AUTH_NUM_ERR_MSG: 'FIND_ID_AUTH_NUM_ERR_MSG' as const,
      AUTH_NUM_INVALID_ERR_MSG: 'FIND_ID_AUTH_NUM_INVALID_ERR_MSG' as const,
      AUTH_NUM_CONFIRM_MSG: 'FIND_ID_AUTH_NUM_CONFIRM_MSG' as const,
      AUTH_NUM_SENT_MSG: 'FIND_ID_AUTH_NUM_SENT_MSG' as const,
      AUTH_NUM_SUCCESS_MSG: 'FIND_ID_AUTH_NUM_SUCCESS_MSG' as const,
      AUTH_NUM_RESEND_AFTER_ONE_MINUTE_MSG: 'FIND_ID_AUTH_NUM_RESEND_AFTER_ONE_MINUTE_MSG' as const,
      AUTH_NUM_OVER_VERIFY_TIME_MSG: 'FIND_ID_AUTH_NUM_OVER_VERIFY_TIME_MSG' as const,
    },
    PW: {
      // ID
      ID: 'FIND_PW_ID' as const,
      ID_IS_ERR: 'FIND_PW_ID_IS_ERR' as const,
      ID_ERR_MSG: 'FIND_PW_ID_ERR_MSG' as const,
      ID_BLANK_ERR_MSG: 'FIND_PW_ID_BLANK_ERR_MSG' as const,

      // NAME
      NAME: 'FIND_PW' as const,
      NAME_IS_ERR: 'FIND_PW_IS_ERR' as const,
      NAME_ERR_MSG: 'FIND_PW_ERR_ERR' as const,
      NAME_BLANK_ERR_MSG: 'FIND_PW_BLANK_ERR_MSG' as const,

      // PHONE
      PHONE: 'FIND_PW_PHONE' as const,
      PHONE_CONFIRM_MSG: 'FIND_PW_PHONE_CONFIRM_MSG' as const,
      PHONE_IS_ERR: 'FIND_PW_PHONE_IS_ERR' as const,
      PHONE_ERR_MSG: 'FIND_PW_PHONE_ERR_MSG' as const,
      PHONE_DUPLICATE_ERR_MSG: 'FIND_PW_PHONE_DUPLICATE_ERR_MSG' as const,
      PHONE_BLANK_ERR_MSG: 'FIND_PW_PHONE_BLANK_ERR_MSG' as const,
      PHONE_REGEX_ERR_MSG: 'FIND_PW_PHONE_REGEX_ERR_MSG' as const,
      PHONE_NOT_REQUESTED_AUTH_ERR_MSG: 'FIND_PW_PHONE_NOT_REQUESTED_AUTH_ERR_MSG' as const,

      // AUTH NUM
      AUTH_NUM: 'FIND_PW_AUTH_NUM' as const,
      AUTH_NUM_IS_ERR: 'FIND_PW_AUTH_NUM_IS_ERR' as const,
      AUTH_NUM_ERR_MSG: 'FIND_PW_AUTH_NUM_ERR_MSG' as const,
      AUTH_NUM_INVALID_ERR_MSG: 'FIND_PW_AUTH_NUM_INVALID_ERR_MSG' as const,
      AUTH_NUM_CONFIRM_MSG: 'FIND_PW_AUTH_NUM_CONFIRM_MSG' as const,
      AUTH_NUM_SENT_MSG: 'FIND_PW_AUTH_NUM_SENT_MSG' as const,
      AUTH_NUM_SUCCESS_MSG: 'FIND_PW_AUTH_NUM_SUCCESS_MSG' as const,
      AUTH_NUM_RESEND_AFTER_ONE_MINUTE_MSG: 'FIND_PW_AUTH_NUM_RESEND_AFTER_ONE_MINUTE_MSG' as const,
      AUTH_NUM_OVER_VERIFY_TIME_MSG: 'FIND_PW_AUTH_NUM_OVER_VERIFY_TIME_MSG' as const,

      // PW
      PW: 'FIND_PW_PW' as const,
      PW_IS_ERR: 'FIND_PW_PW_IS_ERR' as const,
      PW_ERR_MSG: 'FIND_PW_PW_ERR_MSG' as const,
      PW_BLANK_ERR_MSG: 'FIND_PW_PW_BLANK_ERR_MSG' as const,
      PW_REGEX_ERR_MSG: 'FIND_PW_PW_REGEX_ERR_MSG' as const,

      // PW REPEAT
      PW_REPEAT: 'FIND_PW_PW_REPEAT' as const,
      PW_REPEAT_IS_ERR: 'FIND_PW_PW_REPEAT_IS_ERR' as const,
      PW_REPEAT_ERR_MSG: 'FIND_PW_PW_REPEAT_ERR_MSG' as const,
      PW_REPEAT_BLANK_ERR_MSG: 'FIND_PW_PW_REPEAT_BLANK_ERR_MSG' as const,
      PW_REPEAT_UNSAME_ERR_MSG: 'FIND_PW_PW_REPEAT_UNSAME_ERR_MSG' as const,
    },
  },
  LOGIN: {
    // ID
    ID: 'LOGIN_ID' as const,
    ID_IS_ERR: 'LOGIN_ID_IS_ERR' as const,
    ID_ERR_MSG: 'LOGIN_ID_ERR_MSG' as const,

    // PW
    PW: 'LOGIN_PW' as const,
    PW_IS_ERR: 'LOGIN_PW_IS_ERR' as const,
    PW_ERR_MSG: 'LOGIN_PW_ERR_MSG' as const,

    // FAIL MSG
    FAIL_MSG: 'LOGIN_FAIL_MSG' as const,
  },
  GUARDIAN: {
    REQUEST: {
      REQUEST_SUCCESS_MODAL: 'GUARDIAN_REQUEST_SUCCESS_MODAL' as const,
      REGISTER_AND_REQUEST_SUCCESS_MODAL: 'GUARDIAN_REGISTER_AND_REQUEST_SUCCESS_MODAL' as const,

      REGISTER_IS_MONTH_OPEN: 'GUARDIAN_REQUEST_REGISTER_IS_MONTH_OPEN' as const,

      REGISTER_IS_DUPLICATED_ID: 'GUARDIAN_REQUEST_REGISTER_IS_DUPLICATED_ID' as const,
      REGISTER_IS_SAME_PW_AND_PW_CONFIRM: 'GUARDIAN_REQUEST_REGISTER_IS_SAME_PW_AND_PW_CONFIRM' as const,
      REGISTER_IS_SENT_AUTH_NUM: 'GUARDIAN_REQUEST_REGISTER_IS_SENT_AUTH_NUM' as const,
      REGISTER_IS_VERIFIED_AUTH_NUM: 'GUARDIAN_REQUEST_REGISTER_VERIFIED_AUTH_NUM' as const,

      REGISTER_IS_OVER_AUTH_TIME: 'GUARDIAN_REQUEST_REGISTER_IS_OVER_AUTH_TIME' as const,
      REGISTER_TIME_VALUE_OF_AVAILABLE_RESENT_AUTH_NUM:
        'GUARDIAN_REQUEST_REGISTER_TIME_VALUE_OF_AVAILABLE_RESENT_AUTH_NUM' as const,

      SELECT_LOCATION_MODAL_OPEN: 'GUARDIAN_REQUEST_SELECT_LOCATION_MODAL_OPEN' as const,
      NOW_SELECTING_LOCATION_KEY: 'GUARDIAN_REQUEST_NOW_SELECTING_LOCATION_KEY' as const,

      NOW_VIEWING: 'GUARDIAN_REQUEST_NOW_VIEWING' as const,

      LOCATION_SELECTION_NEXT_KEY: 'GUARDIAN_REQUEST_LOCATION_SELECTION_NEXT_KEY' as const,

      SERVICE_INFORMATION_IN_PHASE1: {
        TITLE: 'GUARDIAN_REQUEST_SERVICE_INFORMATION_IN_PHASE1_TITLE' as const,
        DESCRIPTION: 'GUARDIAN_REQUEST_SERVICE_INFORMATION_IN_PHASE1_DESCRIPTION' as const,
      },

      // Input values
      INPUT: {
        DISEASE: 'GUARDIAN_REQUEST_INPUT_DISEASE' as const,

        // ID
        LOGIN_ID: 'GUARDIAN_REQUEST_INPUT_LOGIN_ID' as const,
        LOGIN_ID_IS_ERR: 'GUARDIAN_REQUEST_INPUT_LOGIN_ID_IS_ERR' as const,

        // PW
        LOGIN_PW: 'GUARDIAN_REQUEST_INPUT_LOGIN_PW' as const,
        LOGIN_PW_IS_ERR: 'GUARDIAN_REQUEST_INPUT_LOGIN_PW_IS_ERR' as const,

        // ID
        REGISTER_ID: 'GUARDIAN_REQUEST_INPUT_REGISTER_ID' as const,
        REGISTER_ID_IS_ERR: 'GUARDIAN_REQUEST_INPUT_REGISTER_ID_IS_ERR' as const,

        // PW
        REGISTER_PW: 'GUARDIAN_REQUEST_INPUT_REGISTER_PW' as const,
        REGISTER_PW_IS_ERR: 'GUARDIAN_REQUEST_INPUT_REGISTER_PW_IS_ERR' as const,

        // PW REPEAT
        REGISTER_PW_CONFIRM: 'GUARDIAN_REQUEST_INPUT_REGISTER_PW_CONFIRM' as const,
        REGISTER_PW_CONFIRM_IS_ERR: 'GUARDIAN_REQUEST_INPUT_REGISTER_PW_CONFIRM_IS_ERR' as const,

        // NAME
        REGISTER_NAME: 'GUARDIAN_REQUEST_INPUT_REGISTER_NAME' as const,
        REGISTER_NAME_IS_ERR: 'GUARDIAN_REQUEST_INPUT_REGISTER_NAME_IS_ERR' as const,

        // PHONE
        ENTER_PHONE: 'GUARDIAN_REQUEST_INPUT_ENTER_PHONE' as const,
        ENTER_PHONE_IS_ERR: 'GUARDIAN_REQUEST_INPUT_ENTER_PHONE_IS_ERR' as const,

        // AUTH NUM
        REGISTER_AUTH_NUM: 'GUARDIAN_REQUEST_INPUT_REGISTER_AUTH_NUM' as const,
        REGISTER_AUTH_NUM_IS_ERR: 'GUARDIAN_REQUEST_INPUT_REGISTER_AUTH_NUM_IS_ERR' as const,

        // YEAR
        REGISTER_YEAR: 'GUARDIAN_REQUEST_INPUT_REGISTER_YEAR' as const,
        REGISTER_YEAR_IS_ERR: 'GUARDIAN_REQUEST_INPUT_REGISTER_YEAR_IS_ERR' as const,

        // MONTH
        REGISTER_MONTH: 'GUARDIAN_REQUEST_INPUT_REGISTER_MONTH' as const,
        REGISTER_MONTH_IS_ERR: 'GUARDIAN_REQUEST_INPUT_REGISTER_MONTH_IS_ERR' as const,

        // DAY
        REGISTER_DAY: 'GUARDIAN_REQUEST_INPUT_REGISTER_DAY' as const,
        REGISTER_DAY_IS_ERR: 'GUARDIAN_REQUEST_INPUT_REGISTER_DAY_IS_ERR' as const,

        // ENTIRE_AGREEMENT
        REGISTER_ENTIRE_AGREEMENT: 'GUARDIAN_REQUEST_INPUT_REGISTER_ENTIRE_AGREEMENT' as const,

        // USE_AND_PRIVACY_POLICY_AGREEMENT
        REGISTER_USE_AND_PRIVACY_POLICY_AGREEMENT: 'GUARDIAN_REQUEST_INPUT_REGISTER_USE_AND_PRIVACY_POLICY_AGREEMENT' as const,

        // BASED_ON_GEOLOCATION_AGREEMENT
        REGISTER_BASED_ON_GEOLOCATION_AGREEMENT: 'GUARDIAN_REQUEST_INPUT_REGISTER_BASED_ON_GEOLOCATION_AGREEMENT' as const,

        // GET_ADVERTISE_AGREEMENT
        REGISTER_GET_ADVERTISE_AGREEMENT: 'GUARDIAN_REQUEST_INPUT_REGISTER_GET_ADVERTISE_AGREEMENT' as const,
      },

      // For Selected value By User
      SELECTED: {
        SERVICE_TYPE: 'GUARDIAN_REQUEST_SELECTED_SERVICE_TYPE' as const,
        LOCATIONS: 'GUARDIAN_REQUEST_SELECTED_LOCATIONS' as const,
        GENDER: 'GUARDIAN_REQUEST_SELECTED_GENDER' as const,
        AGE: 'GUARDIAN_REQUEST_SELECTED_AGE' as const,
        GRADE: 'GUARDIAN_REQUEST_SELECTED_GRADE' as const,
        QUALIFICATION: 'GUARDIAN_REQUEST_SELECTED_QUALIFICATION' as const,
        DISEASES: 'GUARDIAN_REQUEST_SELECTED_DISEASES' as const,
        SPECIALTIES: 'GUARDIAN_REQUEST_SELECTED_SPECIALTIES' as const,
        COMMENTS: 'GUARDIAN_REQUEST_SELECTED_COMMENTS' as const,
      },

      // Confirm
      CONFIRM_MSG: {
        REGISTER_ID_AVAILABLE_CONFIRM_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_ID_AVAILABLE_CONFIRM_MSG' as const,

        REGISTER_ID_CONFIRM_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_ID_CONFIRM_MSG' as const,

        REGISTER_AUTH_NUM_CONFIRM_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_AUTH_NUM_CONFIRM_MSG' as const,
        REGISTER_AUTH_NUM_SENT_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_AUTH_NUM_SENT_MSG' as const,
        REGISTER_AUTH_NUM_SUCCESS_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_AUTH_NUM_SUCCESS_MSG' as const,
      },

      // Error
      ERROR_MSG: {
        SERVICE_TYPE: 'GUARDIAN_REQUEST_SELECTED_SERVICE_TYPE_ERROR_MSG' as const,
        LOCATIONS: 'GUARDIAN_REQUEST_SELECTED_LOCATIONS_ERROR_MSG' as const,
        GENDER: 'GUARDIAN_REQUEST_SELECTED_GENDER_ERROR_MSG' as const,
        AGE: 'GUARDIAN_REQUEST_SELECTED_AGE_ERROR_MSG' as const,
        GRADE: 'GUARDIAN_REQUEST_SELECTED_GRADE_ERROR_MSG' as const,
        QUALIFICATION: 'GUARDIAN_REQUEST_SELECTED_QUALIFICATION_ERROR_MSG' as const,
        DISEASES: 'GUARDIAN_REQUEST_SELECTED_DISEASES_ERROR_MSG' as const,
        DISEASES_ETC: 'GUARDIAN_REQUEST_SELECTED_DISEASES_ETC_ERROR_MSG' as const,
        COMMENT: 'GUARDIAN_REQUEST_SELECTED_COMMENT_ERROR_MSG' as const,

        ENTER_PHONE_ERR_MSG: 'GUARDIAN_REQUEST_ENTER_PHONE_ERROR_MSG' as const,
        ENTER_PHONE_BLANK_ERR_MSG: 'GUARDIAN_REQUEST_ENTER_PHONE_BLANK_ERROR_MSG' as const,
        ENTER_PHONE_REGEX_ERR_MSG: 'GUARDIAN_REQUEST_ENTER_PHONE_REGEX_ERROR_MSG' as const,

        LOGIN_FAIL_MSG: 'LOGIN_FAIL_MSG' as const,

        LOGIN_ID_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_LOGIN_ID_ERR_MSG' as const,
        LOGIN_ID_BLANK_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_LOGIN_ID_BLANK_ERR_MSG' as const,

        LOGIN_PW_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_LOGIN_PW_ERR_MSG' as const,
        LOGIN_PW_BLANK_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_LOGIN_PW_BLANK_ERR_MSG' as const,
        LOGIN_UNAVAILABLE_INSTITUTE_USER_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_LOGIN_UNAVAILABLE_INSTITUTE_USER_ERR_MSG' as const,

        REGISTER_ID_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_ID_ERR_MSG' as const,
        REGISTER_ID_BLANK_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_ID_BLANK_ERR_MSG' as const,
        REGISTER_ID_REGEX_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_ID_REGEX_ERR_MSG' as const,
        REGISTER_ID_DUPLICATE_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_ID_DUPLICATE_ERR_MSG' as const,

        REGISTER_PW_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_PW_ERR_MSG' as const,
        REGISTER_PW_BLANK_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_PW_BLANK_ERR_MSG' as const,
        REGISTER_PW_REGEX_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_PW_REGEX_ERR_MSG' as const,

        REGISTER_PW_CONFIRM_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_PW_CONFIRM_ERR_MSG' as const,
        REGISTER_PW_CONFIRM_BLANK_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_PW_CONFIRM_BLANK_ERR_MSG' as const,
        REGISTER_PW_CONFIRM_UNSAME_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_PW_CONFIRM_UNSAME_ERR_MSG' as const,

        REGISTER_NAME_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_NAME_ERR_ERR' as const,
        REGISTER_NAME_BLANK_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_NAME_BLANK_ERR_MSG' as const,

        REGISTER_AUTH_NUM_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_AUTH_NUM_ERR_MSG' as const,
        REGISTER_AUTH_NUM_BLANK_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_AUTH_NUM_BLANK_ERR_MSG' as const,
        REGISTER_AUTH_NUM_INVALID_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_AUTH_NUM_INVALID_ERR_MSG' as const,
        REGISTER_AUTH_NUM_NOT_SENT_AUTH_NUM_ERR_MSG:
          'GUARDIAN_REQUEST_INPUT_REGISTER_AUTH_NUM_NOT_SENT_AUTH_NUM_ERR_MSG' as const,

        REGISTER_BIRTH_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_BIRTH_ERR_MSG' as const,

        REGISTER_YEAR_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_YEAR_ERR_MSG' as const,
        REGISTER_YEAR_BLANK_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_YEAR_BLANK_ERR_MSG' as const,
        REGISTER_YEAR_REGEX_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_YEAR_REGEX_ERR_MSG' as const,

        REGISTER_MONTH_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_MONTH_ERR_MSG' as const,
        REGISTER_MONTH_BLANK_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_MONTH_BLANK_ERR_MSG' as const,
        REGISTER_MONTH_REGEX_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_MONTH_REGEX_ERR_MSG' as const,

        REGISTER_DAY_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_DAY_ERR_MSG' as const,
        REGISTER_DAY_BLANK_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_DAY_BLANK_ERR_MSG' as const,
        REGISTER_DAY_REGEX_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_DAY_REGEX_ERR_MSG' as const,

        REGISTER_AGREEMENT_ERR_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_AGREEMENT_ERR_MSG' as const,

        REGISTER_FAIL_MSG: 'GUARDIAN_REQUEST_INPUT_REGISTER_FAIL_MSG' as const,
      },

      // For Type values from API Server
      EXAMPLES: {
        LOCATION_LISTS: 'GUARDIAN_REQUEST_EXAMPLE_LOCATION_LISTS' as const,
        GENDER_TYPES: 'GUARDIAN_REQUEST_EXAMPLE_GENDER_TYPES' as const,
        AGE_TYPES: 'GUARDIAN_REQUEST_EXAMPLE_AGE_TYPES' as const,
        GRADE_TYPES: 'GUARDIAN_REQUEST_EXAMPLE_GRADE_TYPES' as const,
        QUALIFICATION_TYPES: 'GUARDIAN_REQUEST_EXAMPLE_QUALIFICATION_TYPES' as const,
        DISEASE_TYPES: 'GUARDIAN_REQUEST_EXAMPLE_DISEASE_TYPES' as const,
        SPECIALTY_TYPES: 'GUARDIAN_REQUEST_EXAMPLE_SPECIALTY_TYPES' as const,
        COMMENT_TYPES: 'GUARDIAN_REQUEST_EXAMPLE_COMMENT_TYPES' as const,
      },
    },
    REGISTER: {
      LOCATION_LISTS: 'GUARDIAN_REGISTER_LOCATION_LISTS' as const,

      // ID
      ID: 'GUARDIAN_REGISTER_ID' as const,
      ID_IS_ERR: 'GUARDIAN_REGISTER_ID_IS_ERR' as const,
      ID_ERR_MSG: 'GUARDIAN_REGISTER_ID_ERR_MSG' as const,
      ID_BLANK_ERR_MSG: 'GUARDIAN_REGISTER_ID_BLANK_ERR_MSG' as const,
      ID_REGEX_ERR_MSG: 'GUARDIAN_REGISTER_ID_REGEX_ERR_MSG' as const,
      ID_DUPLICATE_ERR_MSG: 'GUARDIAN_REGISTER_ID_DUPLICATE_ERR_MSG' as const,
      ID_CONFIRM_MSG: 'GUARDIAN_REGISTER_ID_CONFIRM_MSG' as const,
      ID_AVAILABLE_CONFIRM_MSG: 'GUARDIAN_REGISTER_ID_AVAILABLE_CONFIRM_MSG' as const,

      // PW
      PW: 'GUARDIAN_REGISTER_PW' as const,
      PW_IS_ERR: 'GUARDIAN_REGISTER_PW_IS_ERR' as const,
      PW_ERR_MSG: 'GUARDIAN_REGISTER_PW_ERR_MSG' as const,
      PW_BLANK_ERR_MSG: 'GUARDIAN_REGISTER_PW_BLANK_ERR_MSG' as const,
      PW_REGEX_ERR_MSG: 'GUARDIAN_REGISTER_PW_REGEX_ERR_MSG' as const,

      // PW REPEAT
      PW_REPEAT: 'GUARDIAN_REGISTER_PW_REPEAT' as const,
      PW_REPEAT_IS_ERR: 'GUARDIAN_REGISTER_PW_REPEAT_IS_ERR' as const,
      PW_REPEAT_ERR_MSG: 'GUARDIAN_REGISTER_PW_REPEAT_ERR_MSG' as const,
      PW_REPEAT_BLANK_ERR_MSG: 'GUARDIAN_REGISTER_PW_REPEAT_BLANK_ERR_MSG' as const,
      PW_REPEAT_UNSAME_ERR_MSG: 'GUARDIAN_REGISTER_PW_REPEAT_UNSAME_ERR_MSG' as const,

      // NAME
      NAME: 'GUARDIAN_REGISTER_NAME' as const,
      NAME_IS_ERR: 'GUARDIAN_REGISTER_NAME_IS_ERR' as const,
      NAME_ERR_MSG: 'GUARDIAN_REGISTER_NAME_ERR_ERR' as const,
      NAME_BLANK_ERR_MSG: 'GUARDIAN_REGISTER_NAME_BLANK_ERR_MSG' as const,

      // PHONE
      PHONE: 'GUARDIAN_REGISTER_PHONE' as const,
      PHONE_CONFIRM_MSG: 'GUARDIAN_REGISTER_PHONE_CONFIRM_MSG' as const,
      PHONE_IS_ERR: 'GUARDIAN_REGISTER_PHONE_IS_ERR' as const,
      PHONE_ERR_MSG: 'GUARDIAN_REGISTER_PHONE_ERR_MSG' as const,
      PHONE_DUPLICATE_ERR_MSG: 'GUARDIAN_REGISTER_PHONE_DUPLICATE_ERR_MSG' as const,
      PHONE_BLANK_ERR_MSG: 'GUARDIAN_REGISTER_PHONE_BLANK_ERR_MSG' as const,
      PHONE_REGEX_ERR_MSG: 'GUARDIAN_REGISTER_PHONE_REGEX_ERR_MSG' as const,
      PHONE_NOT_REQUESTED_AUTH_ERR_MSG: 'GUARDIAN_REGISTER_PHONE_NOT_REQUESTED_AUTH_ERR_MSG' as const,

      // AUTH NUM
      AUTH_NUM: 'GUARDIAN_REGISTER_AUTH_NUM' as const,
      AUTH_NUM_IS_ERR: 'GUARDIAN_REGISTER_AUTH_NUM_IS_ERR' as const,
      AUTH_NUM_ERR_MSG: 'GUARDIAN_REGISTER_AUTH_NUM_ERR_MSG' as const,
      AUTH_NUM_INVALID_ERR_MSG: 'GUARDIAN_REGISTER_AUTH_NUM_INVALID_ERR_MSG' as const,
      AUTH_NUM_CONFIRM_MSG: 'GUARDIAN_REGISTER_AUTH_NUM_CONFIRM_MSG' as const,
      AUTH_NUM_SENT_MSG: 'GUARDIAN_REGISTER_AUTH_NUM_SENT_MSG' as const,
      AUTH_NUM_SUCCESS_MSG: 'GUARDIAN_REGISTER_AUTH_NUM_SUCCESS_MSG' as const,
      AUTH_NUM_RESEND_AFTER_ONE_MINUTE_MSG: 'AUTH_NUM_RESEND_AFTER_ONE_MINUTE_MSG' as const,
      AUTH_NUM_OVER_VERIFY_TIME_MSG: 'AUTH_NUM_OVER_VERIFY_TIME_MSG' as const,

      BIRTH_ERR_MSG: 'GUARDIAN_REGISTER_BIRTH_ERR_MSG' as const,

      // YEAR
      YEAR: 'GUARDIAN_REGISTER_YEAR' as const,
      YEAR_IS_ERR: 'GUARDIAN_REGISTER_YEAR_IS_ERR' as const,
      YEAR_BLANK_ERR_MSG: 'GUARDIAN_REGISTER_YEAR_BLANK_ERR_MSG' as const,
      YEAR_REGEX_ERR_MSG: 'GUARDIAN_REGISTER_YEAR_REGEX_ERR_MSG' as const,

      // MONTH
      MONTH: 'GUARDIAN_REGISTER_MONTH' as const,
      MONTH_IS_ERR: 'GUARDIAN_REGISTER_MONTH_IS_ERR' as const,
      MONTH_BLANK_ERR_MSG: 'GUARDIAN_REGISTER_MONTH_BLANK_ERR_MSG' as const,
      MONTH_REGEX_ERR_MSG: 'GUARDIAN_REGISTER_MONTH_REGEX_ERR_MSG' as const,

      // DAY
      DAY: 'GUARDIAN_REGISTER_DAY' as const,
      DAY_IS_ERR: 'GUARDIAN_REGISTER_DAY_IS_ERR' as const,
      DAY_BLANK_ERR_MSG: 'GUARDIAN_REGISTER_DAY_BLANK_ERR_MSG' as const,
      DAY_REGEX_ERR_MSG: 'GUARDIAN_REGISTER_DAY_REGEX_ERR_MSG' as const,

      AGREEMENT_ERR_MSG: 'GUARDIAN_REGISTER_AGREEMENT_ERR_MSG' as const,

      // ENTIRE_AGREEMENT
      ENTIRE_AGREEMENT: 'GUARDIAN_REGISTER_ENTIRE_AGREEMENT' as const,

      // USE_AND_PRIVACY_POLICY_AGREEMENT
      USE_AND_PRIVACY_POLICY_AGREEMENT: 'GUARDIAN_REGISTER_USE_AND_PRIVACY_POLICY_AGREEMENT' as const,

      // BASED_ON_GEOLOCATION_AGREEMENT
      BASED_ON_GEOLOCATION_AGREEMENT: 'GUARDIAN_REGISTER_BASED_ON_GEOLOCATION_AGREEMENT' as const,

      // GET_ADVERTISE_AGREEMENT
      GET_ADVERTISE_AGREEMENT: 'GUARDIAN_REGISTER_GET_ADVERTISE_AGREEMENT' as const,

      // FAIL MSG
      FAIL_MSG: 'GUARDIAN_REGISTER_FAIL_MSG' as const,
    },
  },
  INSTITUTE: {
    REGISTER: {
      POSITION_LISTS: 'INSTITUTE_REGISTER_POSITION_LISTS' as const,
      LOCATION_LISTS: 'INSTITUTE_REGISTER_LOCATION_LISTS' as const,

      // ID
      ID: 'INSTITUTE_REGISTER_ID' as const,
      ID_IS_ERR: 'INSTITUTE_REGISTER_ID_IS_ERR' as const,
      ID_ERR_MSG: 'INSTITUTE_REGISTER_ID_ERR_MSG' as const,
      ID_BLANK_ERR_MSG: 'INSTITUTE_REGISTER_ID_BLANK_ERR_MSG' as const,
      ID_REGEX_ERR_MSG: 'INSTITUTE_REGISTER_ID_REGEX_ERR_MSG' as const,
      ID_DUPLICATE_ERR_MSG: 'INSTITUTE_REGISTER_ID_DUPLICATE_ERR_MSG' as const,
      ID_CONFIRM_MSG: 'INSTITUTE_REGISTER_ID_CONFIRM_MSG' as const,
      ID_AVAILABLE_CONFIRM_MSG: 'INSTITUTE_REGISTER_ID_AVAILABLE_CONFIRM_MSG' as const,

      // PW
      PW: 'INSTITUTE_REGISTER_PW' as const,
      PW_IS_ERR: 'INSTITUTE_REGISTER_PW_IS_ERR' as const,
      PW_ERR_MSG: 'INSTITUTE_REGISTER_PW_ERR_MSG' as const,
      PW_BLANK_ERR_MSG: 'INSTITUTE_REGISTER_PW_BLANK_ERR_MSG' as const,
      PW_REGEX_ERR_MSG: 'INSTITUTE_REGISTER_PW_REGEX_ERR_MSG' as const,

      // PW REPEAT
      PW_REPEAT: 'INSTITUTE_REGISTER_PW_REPEAT' as const,
      PW_REPEAT_IS_ERR: 'INSTITUTE_REGISTER_PW_REPEAT_IS_ERR' as const,
      PW_REPEAT_ERR_MSG: 'INSTITUTE_REGISTER_PW_REPEAT_ERR_MSG' as const,
      PW_REPEAT_BLANK_ERR_MSG: 'INSTITUTE_REGISTER_PW_REPEAT_BLANK_ERR_MSG' as const,
      PW_REPEAT_UNSAME_ERR_MSG: 'INSTITUTE_REGISTER_PW_REPEAT_UNSAME_ERR_MSG' as const,

      // NAME
      NAME: 'INSTITUTE_REGISTER_NAME' as const,
      NAME_IS_ERR: 'INSTITUTE_REGISTER_NAME_IS_ERR' as const,
      NAME_ERR_MSG: 'INSTITUTE_REGISTER_NAME_ERR_ERR' as const,
      NAME_BLANK_ERR_MSG: 'INSTITUTE_REGISTER_NAME_BLANK_ERR_MSG' as const,

      // PHONE
      PHONE: 'INSTITUTE_REGISTER_PHONE' as const,
      PHONE_IS_ERR: 'INSTITUTE_REGISTER_PHONE_IS_ERR' as const,
      PHONE_CONFIRM_MSG: 'INSTITUTE_REGISTER_PHONE_CONFIRM_MSG' as const,
      PHONE_ERR_MSG: 'INSTITUTE_REGISTER_PHONE_ERR_MSG' as const,
      PHONE_DUPLICATE_ERR_MSG: 'INSTITUTE_REGISTER_PHONE_DUPLICATE_ERR_MSG' as const,
      PHONE_BLANK_ERR_MSG: 'INSTITUTE_REGISTER_PHONE_BLANK_ERR_MSG' as const,
      PHONE_REGEX_ERR_MSG: 'INSTITUTE_REGISTER_PHONE_REGEX_ERR_MSG' as const,
      PHONE_NOT_REQUESTED_AUTH_ERR_MSG: 'INSTITUTE_REGISTER_PHONE_NOT_REQUESTED_AUTH_ERR_MSG' as const,

      // AUTH NUM
      AUTH_NUM: 'INSTITUTE_REGISTER_AUTH_NUM' as const,
      AUTH_NUM_IS_ERR: 'INSTITUTE_REGISTER_AUTH_NUM_IS_ERR' as const,
      AUTH_NUM_ERR_MSG: 'INSTITUTE_REGISTER_AUTH_NUM_ERR_MSG' as const,
      AUTH_NUM_INVALID_ERR_MSG: 'INSTITUTE_REGISTER_AUTH_NUM_INVALID_ERR_MSG' as const,
      AUTH_NUM_CONFIRM_MSG: 'INSTITUTE_REGISTER_AUTH_NUM_CONFIRM_MSG' as const,
      AUTH_NUM_SENT_MSG: 'INSTITUTE_REGISTER_AUTH_NUM_SENT_MSG' as const,
      AUTH_NUM_SUCCESS_MSG: 'INSTITUTE_REGISTER_AUTH_NUM_SUCCESS_MSG' as const,
      AUTH_NUM_RESEND_AFTER_ONE_MINUTE_MSG: 'AUTH_NUM_RESEND_AFTER_ONE_MINUTE_MSG' as const,
      AUTH_NUM_OVER_VERIFY_TIME_MSG: 'AUTH_NUM_OVER_VERIFY_TIME_MSG' as const,

      BIRTH_ERR_MSG: 'INSTITUTE_REGISTER_BIRTH_ERR_MSG' as const,

      // YEAR
      YEAR: 'INSTITUTE_REGISTER_YEAR' as const,
      YEAR_IS_ERR: 'INSTITUTE_REGISTER_YEAR_IS_ERR' as const,
      YEAR_BLANK_ERR_MSG: 'INSTITUTE_REGISTER_YEAR_BLANK_ERR_MSG' as const,
      YEAR_REGEX_ERR_MSG: 'INSTITUTE_REGISTER_YEAR_REGEX_ERR_MSG' as const,

      // MONTH
      MONTH: 'INSTITUTE_REGISTER_MONTH' as const,
      MONTH_IS_ERR: 'INSTITUTE_REGISTER_MONTH_IS_ERR' as const,
      MONTH_BLANK_ERR_MSG: 'INSTITUTE_REGISTER_MONTH_BLANK_ERR_MSG' as const,
      MONTH_REGEX_ERR_MSG: 'INSTITUTE_REGISTER_MONTH_REGEX_ERR_MSG' as const,

      // DAY
      DAY: 'INSTITUTE_REGISTER_DAY' as const,
      DAY_IS_ERR: 'INSTITUTE_REGISTER_DAY_IS_ERR' as const,
      DAY_BLANK_ERR_MSG: 'INSTITUTE_REGISTER_DAY_BLANK_ERR_MSG' as const,
      DAY_REGEX_ERR_MSG: 'INSTITUTE_REGISTER_DAY_REGEX_ERR_MSG' as const,

      AGREEMENT_ERR_MSG: 'INSTITUTE_REGISTER_AGREEMENT_ERR_MSG' as const,

      // ENTIRE_AGREEMENT
      ENTIRE_AGREEMENT: 'INSTITUTE_REGISTER_ENTIRE_AGREEMENT' as const,

      // USE_AND_PRIVACY_POLICY_AGREEMENT
      USE_AND_PRIVACY_POLICY_AGREEMENT: 'INSTITUTE_REGISTER_USE_AND_PRIVACY_POLICY_AGREEMENT' as const,

      // BASED_ON_GEOLOCATION_AGREEMENT
      BASED_ON_GEOLOCATION_AGREEMENT: 'INSTITUTE_REGISTER_BASED_ON_GEOLOCATION_AGREEMENT' as const,

      // GET_ADVERTISE_AGREEMENT
      GET_ADVERTISE_AGREEMENT: 'INSTITUTE_REGISTER_GET_ADVERTISE_AGREEMENT' as const,

      // FAIL MSG
      FAIL_MSG: 'INSTITUTE_REGISTER_FAIL_MSG' as const,

      // INSTITUTE BASIC INFO
      BASIC_INFO_INSTITUTE_NAME: 'BASIC_INFO_INSTITUTE_NAME' as const,
      BASIC_INFO_INSTITUTE_NAME_IS_ERR: 'BASIC_INFO_INSTITUTE_NAME_IS_ERR' as const,
      BASIC_INFO_INSTITUTE_NAME_ERR_MSG: 'BASIC_INFO_INSTITUTE_NAME_ERR_MSG' as const,
      BASIC_INFO_INSTITUTE_NAME_BLANK_ERR_MSG: 'BASIC_INFO_INSTITUTE_NAME_BLANK_ERR_MSG' as const,
      BASIC_INFO_INSTITUTE_REPRESENTER_NAME: 'BASIC_INFO_INSTITUTE_REPRESENTER_NAME' as const,
      BASIC_INFO_INSTITUTE_REPRESENTER_NAME_IS_ERR: 'BASIC_INFO_INSTITUTE_REPRESENTER_NAME_IS_ERR' as const,
      BASIC_INFO_INSTITUTE_REPRESENTER_NAME_ERR_MSG: 'BASIC_INFO_INSTITUTE_REPRESENTER_NAME_ERR_MSG' as const,
      BASIC_INFO_INSTITUTE_REPRESENTER_NAME_BLANK_ERR_MSG: 'BASIC_INFO_INSTITUTE_REPRESENTER_NAME_BLANK_ERR_MSG' as const,
      BASIC_INFO_INSTITUTE_ADDRESS: 'BASIC_INFO_INSTITUTE_ADDRESS' as const,
      BASIC_INFO_INSTITUTE_ADDRESS_IS_ERR: 'BASIC_INFO_INSTITUTE_ADDRESS_IS_ERR' as const,
      BASIC_INFO_INSTITUTE_ADDRESS_ERR_MSG: 'BASIC_INFO_INSTITUTE_ADDRESS_ERR_MSG' as const,
      BASIC_INFO_INSTITUTE_ADDRESS_BLANK_ERR_MSG: 'BASIC_INFO_INSTITUTE_ADDRESS_BLANK_ERR_MSG' as const,
    },
  },
};

export default KEY;
